version: '3.8'

services:
  sensor_freio:
    build: .
    container_name: modulo_freios_redundante
    command: python sensor_freio.py
    restart: always

  lider_waic:
    build: .
    container_name: modulo_waic_wireless
    command: python lider_waic.py
    restart: always

  sensores_voo:
    build: .
    container_name: modulo_sistemas_gerais
    command: python sensores_voo.py
    restart: always

  navegacao:
    build: .
    container_name: modulo_navegacao_auto
    command: python computador_navegacao.py
    restart: always

  radar:
    build: .
    container_name: modulo_radar_atc
    command: python radar_externo.py
    restart: always

  fms_api:
    build: .
    container_name: modulo_fms_api
    command: python fms_distribuido.py
    restart: always